include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
 - review
 - build
 - test
 - deploy

variables:
    BUNDLE: "extensions-git.flatpak"
    JS_LOG: "js-report.txt"

image: registry.gitlab.gnome.org/gnome/mutter/fedora/33:x86_64-2021-02-04.1

.only_default: &only_default
    only:
        - branches
        - tags
        - merge_requests

check_commit_log:
    stage: review
    variables:
        GIT_DEPTH: "100"
    script:
        - ./.gitlab-ci/check-commit-log.sh
    only:
        - merge_requests

js_check:
    image: registry.gitlab.gnome.org/gnome/gnome-shell/fedora/33:2020-11-17.0
    stage: review
    script:
        - find js -name '*.js' -exec js78 -c '{}' ';' 2>&1 | tee $JS_LOG
        - (! grep -q . $JS_LOG)
    <<: *only_default
    artifacts:
        paths:
            - ${JS_LOG}
        when: on_failure

eslint:
    image: registry.gitlab.gnome.org/gnome/gnome-shell/fedora/33:2020-11-17.0
    stage: review
    script:
        - ./.gitlab-ci/run-eslint.sh
    <<: *only_default
    artifacts:
        paths:
            - reports
        when: always

potfile_check:
    image: registry.gitlab.gnome.org/gnome/gnome-shell/fedora/33:2020-11-17.0
    stage: review
    script:
        - ./.gitlab-ci/check-potfiles.sh
    <<: *only_default

no_template_check:
    image: registry.gitlab.gnome.org/gnome/gnome-shell/fedora/33:2020-11-17.0
    stage: review
    script:
        - ./.gitlab-ci/check-template-strings.sh
    <<: *only_default

build:
    stage: build
    needs: []
    before_script:
        - .gitlab-ci/checkout-mutter.sh
        - meson mutter mutter/build --prefix=/usr -Dtests=false
        - ninja -C mutter/build install
    script:
        - meson . build -Dbuiltype=debugoptimized -Dman=false --werror
        - ninja -C build
        - ninja -C build install
    <<: *only_default
    artifacts:
        expire_in: 1 day
        paths:
            - mutter
            - build

test:
    stage: test
    needs: ["build"]
    variables:
        XDG_RUNTIME_DIR: "$CI_PROJECT_DIR/runtime-dir"
        NO_AT_BRIDGE: "1"
    before_script:
        - ninja -C mutter/build install
    script:
        - dbus-run-session -- xvfb-run meson test -C build --no-rebuild
    <<: *only_default
    artifacts:
        expire_in: 1 day
        paths:
            - build/meson-logs/testlog.txt
        when: on_failure

flatpak:
    stage: build
    needs: []
    variables:
        SUBPROJECT: "subprojects/extensions-app"
        # Your manifest path
        MANIFEST_PATH: "$SUBPROJECT/build-aux/flatpak/org.gnome.Extensions.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "gnome-extensions-app"
        APP_ID: "org.gnome.Extensions"
    extends: .flatpak
    <<: *only_default

nightly:
  extends: '.publish_nightly'
  variables:
    BUNDLES: '$BUNDLE'
